#! /usr/bin/env python

"""
Sometimes i need to download page content as if i were a browser.
Just a shorthand for wget.
"""

from subprocess import call

def run_wget(filename, url):
    return call(['wget', '--progress=dot', '-U', 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.3) Gecko/20070310 Iceweasel/2.0.0.3 (Debian-2.0.0.3-1)', '-O', '%s' % filename, url])

if __name__ == '__main__':
    from optparse import OptionParser
    parser   = OptionParser()
    parser.add_option("-o", "--output", dest="output",
                      metavar="string", help="The output file.")

    parser.add_option("-u", "--url", dest="url",
                      metavar="string", help="The URL to download from")

    (opt, args) = parser.parse_args()

    if opt.output and opt.url:
        run_wget(opt.output, opt.url)
    else:
        parser.print_help()

